### ISSUE TITLE
Still getting ArgumentException during PieChart animation

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#104]
I raised this on Gitter, but it had only happened once.  Now I'm getting it regularly.

	A first chance exception of type 'System.ArgumentException' occurred in WindowsBase.dll
	System.ApplicationException: Fatal error in GS.SS.Ui.Windsor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null.  Application has ended.  Review log files to determine cause of crash.  Correct problem and restart the application. ---> System.ArgumentException: 'NaN' is not a valid value for property 'To'.
	   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
	   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
	   at System.Windows.Media.Animation.DoubleAnimation.set_To(Nullable`1 value)
	   at LiveCharts.PieSeries.Plot(Boolean animate)
	   at LiveCharts.CoreComponents.Chart.UpdateSeries(Object sender, EventArgs e)
	   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   --- End of inner exception stack trace ---

**Comment by gregsdennis** [comment]
Seems to occur when all values sum to 0.

**Comment by beto-rodriguez** [comment]
Ok, working on it.

**Comment by beto-rodriguez** [comment]
@gregsdennis Yes this error happens when all values sums 0, because there is a zero division (x / 0) when the chart is trying to determine the participation of each slice. 

I could easily just skip the Plot method then the pie sum is zero, sadly this would break animations while the chart is this invalid state, I will force the zero with a numeric approach, so if pie sum is 0 I will force it to be double.maxvalue this way all pie slices participation will trend to zero and the animation should run correctly.

**Comment by gregsdennis** [comment]
Sounds like a good idea.  I expect that the side effects will be rare cases when the pie data is extremely large.  A workaround could be for the client to scale back their data.

**Comment by beto-rodriguez** [comment]
yea, maybe that is the only side effect, but there is no practical use for a client to display a chart with more than 20 slices (maybe if he is using his stadium size screen he would need it)

**Comment by gregsdennis** [comment]
There are a couple pretty big ones here in Texas (Cowboys Stadium & Texas Motor Speedway) 😃
