### ISSUE TITLE
Null Reference Exception at LiveCharts.LineChart.DataMouseEnter

### ISSUE THREAD

**Issue by ajmcateer** [beto-rodriguez/Live-Charts#144]
Here is my code with the stack trace below

Error Happens whenever I move the mouse over the chart. I am using the latest .0.6.7 build

Setting Hoverable to false seems to have fixed it.
           
           public SeriesCollection Series { get; private set; }
           Series = new SeriesCollection();

            var pingSeries = new LineSeries
            {
                Title = "Ping Times",
                Values = new ChartValues<double> { },
                PointRadius = 0
            };

            //add our series to our SeriesCollection
            Series.Add(pingSeries);
            uiContext.Send(x => Series[0].Values.Add((double)pr.RoundtripTime), null);

And the Stack Trace

`  at LiveCharts.LineChart.DataMouseEnter(Object sender, MouseEventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.MouseOverProperty.FireNotifications(UIElement uie, ContentElement ce, UIElement3D uie3D, Boolean oldValue)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action2 originChangedAction)
   at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList1 otherOrigins, DeferredElementTreeState& oldTreeState, Action2 originChangedAction)
   at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by nawrasg** [comment]
I'm having the same problem but Hoverable didn't fix it!

**Comment by beto-rodriguez** [comment]
Hello and thanks for reporting, I am working on this issue, will be fixed in next release, a work around is to use 0.6.6 version.

Thanks!

**Comment by beto-rodriguez** [comment]
This is already fixed, I am sorry about this error, actually I unlisted 0.6.7 version from nugget because of this dummy bug.
