### ISSUE TITLE
Designer throws NullReferenceException

### ISSUE THREAD

**Issue by Lakritzator** [beto-rodriguez/Live-Charts#180]
First, you are really making a cool project!

I had some issues with the nuget 0.7.0, I got a NullReferenceException while trying to create a chart with lines, both RunTime and in the designer.

So I wanted to see how you did it, and had a look at the LineExample. Except for in the designer, your example actually worked, so instead of using the NuGet Package I referenced your projects directly and got things working.

Still the designer somehow doesn't like it.

When I look at the Examples\Wpf\CartesianChart\LineExample\LineExample.xaml the designer shows:
NullReferenceException: Object reference not set to an instance of an object.
Stacktrace:
at LiveCharts.ChartUpdater.InitializeSeriesParams(ISeriesView seriesView)
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick()
   at LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

(Visual Studio 2015 professional Update 2)

P.S.
I would advice you to remove some of the unneeded references, e.g. System.Net.Http is probably never used. You can request an open source license from Jet-Brains for ReSharper, this is definitively worth it!!! (Got one for Greenshot) This can help you to improve code quality and e.g. remove unneeded references.

**Comment by beto-rodriguez** [comment]
Hello and thanks!

I am currently bulding all the examples in the web site and I have found some issues with 0.7.0, some of them do not work with the latest nuget package, I am fixing everything in 0.7.1, almost ready

about the designer I actually was debuing the designer before 0.7.0 release but it is really hard and unpredictable I think visual.studio team has many issues there, I will try to fix designer bugs again later when more features are complete

About resharper, yeah yeah I got mine :smile: the nuget packages do not need hese references, actually the resharper feature that removes unused references do not take away system.http even it is not used, but I think it is more important in .net 40

**Comment by Lakritzator** [comment]
For me it's not a big issue if the designer doesn't work for now, just wanted to make sure it was tracked. Will be waiting impatiently on 0.7.1 :smile:

**Comment by gregsdennis** [comment]
I found [a detailed site](https://msdn.microsoft.com/en-us/library/bb514636(v=vs.100).aspx) on how to debug the designer more easily. Essentially, you're debugging your code in design mode by debugging VS as it attempt to draw.  I was having trouble getting the breakpoint to hit, though.  Will

**Comment by Hogflash** [comment]
Beto,

Thank you for the great project.  Would like to add that I am also seeing the same issue running v0.7.4.1 in the designer with VS2015 community edition Update 1.  The project compiles and runs though.
Stack Trace:
   at LiveCharts.Wpf.Charts.Base.Chart.LoadLegend()
   at LiveCharts.Charts.ChartCore.PlaceLegend(CoreRectangle drawMargin)
   at LiveCharts.Charts.ChartCore.CalculateComponentsAndMargin()
   at LiveCharts.Charts.CartesianChartCore.PrepareAxes()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView)
   at LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 
Thanks,

Gary

**Comment by Hogflash** [comment]
Beto,

I found I could fix the problem by removing LegendLocation="Right" in the lvc:CartesisnChart declaration.  FYI, this is from the Basic Line Chart example.

Here is the XAML that I am using that is broken:
        <lvc:CartesianChart Series="{Binding SeriesCollection}" LegendLocation="Right" >
            <lvc:CartesianChart.AxisY>
                <lvc:Axis Title="Sales" LabelFormatter="{Binding YFormatter}" />
            </lvc:CartesianChart.AxisY>
            <lvc:CartesianChart.AxisX>
                <lvc:Axis Title="Month" Labels="{Binding Labels}" />
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>

Hopes this helps!

Gary

**Comment by beto-rodriguez** [comment]
@Hogflash Thanks Gary, your information helps a lot.

I just fixed the LegendLocation designer bug, it should be already working correctly in the repo, I will publish a Nuget package as soon as I fix all the designer bugs I can.

Thanks for your info again, it is really useful!

**Comment by beto-rodriguez** [comment]
this should solve this issue, testing to close this issue https://github.com/beto-rodriguez/Live-Charts/commit/b1c96dc1e598523ed8116ea33fa784ff7908eb8c

**Comment by beto-rodriguez** [comment]
Closed with https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.7.6 release

**Comment by Hogflash** [comment]
Great!  I verified it is working correctly now, thanks!
