### ISSUE TITLE
Unhandled Exception: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Yukimune** [beto-rodriguez/Live-Charts#276]
Hi.
An unhandled exception has occurred at LineSeries.cs:378, v0.7.8

System.ArgumentOutOfRangeException はハンドルされませんでした。
  HResult=-2146233086
  Message=指定された引数は、有効な値の範囲内にありません。
パラメーター名:index
  ParamName=index
  Source=WindowsBase
  StackTrace:
       場所 MS.Utility.FrugalStructList`1.Insert(Int32 index, T value)
       場所 System.Windows.Media.PathSegmentCollection.Insert(Int32 index, PathSegment value)
       場所 LiveCharts.Wpf.LineSeries.EndSegment(Int32 atIndex, CorePoint location) 場所 D:\Documents\Repos\github\Live-Charts\WpfView\LineSeries.cs:行 378
       場所 LiveCharts.SeriesAlgorithms.LineAlgorithm.Update() 場所 D:\Documents\Repos\github\Live-Charts\Core\SeriesAlgorithms\LineAlgorithm.cs:行 168
       場所 LiveCharts.ChartUpdater.Update(Boolean restartsAnimations) 場所 D:\Documents\Repos\github\Live-Charts\Core\ChartUpdater.cs:行 91
       場所 LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView) 場所 D:\Documents\Repos\github\Live-Charts\WpfView\Components\ChartUpdater.cs:行 78
       場所 LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args) 場所 D:\Documents\Repos\github\Live-Charts\WpfView\Components\ChartUpdater.cs:行 39
       場所 System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
       場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()
       場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       場所 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       場所 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       場所 System.Windows.Threading.DispatcherOperation.Invoke()
       場所 System.Windows.Threading.Dispatcher.ProcessQueue()
       場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       場所 System.Windows.Application.RunDispatcher(Object ignore)
       場所 System.Windows.Application.RunInternal(Window window)
       場所 System.Windows.Application.Run(Window window)
       場所 System.Windows.Application.Run()
       場所 OperationObserver.Viewer.App.Main()
  InnerException: 

Do you need any other details? Thank you;)

**Comment by Yukimune** [comment]
I've updated them from v0.7.6. then came to watch the exception.

**Comment by Yukimune** [comment]
I solved it, maybe my code cause it.
So, I close for now. Thank you!

**Comment by carlmichaelbenson** [comment]
@Yukimune I am seeing a similar error... What did you change in your code to solve this?

**Comment by carlmichaelbenson** [comment]
@Yukimune I am seeing a similar error... What did you change in your code to solve this?

**Comment by carlmichaelbenson** [comment]
Using v0.9.6 release binaries and geared v1.2.5 in our WPF app... 

This is our recurring exception... 

Stellinity2.ControlRoom2.GUI.exe
2017-11-10 15:00:25.54946 [1]
ERROR Stellinity2.ControlRoom2.GUI.App
Error: DispatcherUnhandledException

Event: Application.Current.DispatcherUnhandledException
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at MS.Utility.FrugalStructList`1.Insert(Int32 index, T value)
   at System.Windows.Media.PathSegmentCollection.Insert(Int32 index, PathSegment value)
   at LiveCharts.Wpf.LineSeries.EndSegment(Int32 atIndex, CorePoint location)
   at LiveCharts.SeriesAlgorithms.LineAlgorithm.Update()
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force)
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by NiverplastDieuwert** [comment]
Is there any news? I have the same issue (v0.9.7):

   at MS.Utility.FrugalStructList`1.Insert(Int32 index, T value)
   at System.Windows.Media.PathSegmentCollection.Insert(Int32 index, PathSegment value)
   at LiveCharts.Wpf.LineSeries.EndSegment(Int32 atIndex, CorePoint location) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\LineSeries.cs:line 480
   at LiveCharts.SeriesAlgorithms.LineAlgorithm.Update() in c:\Users\btord\Documents\Projects\LiveCharts\Core40\SeriesAlgorithms\LineAlgorithm.cs:line 188
   at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force) in c:\Users\btord\Documents\Projects\LiveCharts\Core40\ChartUpdater.cs:line 125
   at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Components\ChartUpdater.cs:line 89
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Application...
