### ISSUE TITLE
NullReferenceException in chart with multiple line series when one point is double.NaN

### ISSUE THREAD

**Issue by AndyConlisk** [beto-rodriguez/Live-Charts#278]
In a WPF app I am building. I have a chart with 2 line series. One set contained data from Age 21 to Age 80. Second Set contained data from Age 27 to Age 80. The second set of data had Double.NaN set for any missing points (so 21-26).

When hovering over a point that had the Double.NaN set in the second set, the app would crash.  With a NullReferenceException.

Here is a truncated Trace Record of the crash. Seem to happen in the DataMouseEnter function. 

```
Activated	Event	Time	Duration	Thread
	<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>RiskPredictionModel.WPF.vshost.exe</AppDomain><Exception><ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   at LiveCharts.Wpf.Charts.Base.Chart.&amp;lt;&amp;gt;c.&amp;lt;DataMouseEnter&amp;gt;b__123_2(ChartPoint x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LiveCharts.Wpf.Charts.Base.Chart.DataMouseEnter(Object sender, EventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object 

```

Here is an animation of the crash. 

![animation](https://cloud.githubusercontent.com/assets/1823308/17033163/6522e9ec-4f42-11e6-807c-2de35704ed44.gif)

Here is a snippet of the code. 

```
        public SeriesCollection RiskCollection
        {
            get
            {                 
                return new SeriesCollection
                {
                    CalculatedRisk,
                    AverageRisk
                };
            }

        }

        public LineSeries CalculatedRisk
        {
            get
            {
                if (_calculatedRisk != null && _calculatedRisk.Count > 0)
                {
                    return new LineSeries
                    {
                        Values = _calculatedRisk,
                        Title = "Calculated Risk"
                    };
                }
                    
                var risk = _resultSet.ResultItems.OrderBy(x => x.Age);

                _calculatedRisk = new ChartValues<double>();          
                
                for(var i = _averageResultSet.ResultItems.OrderBy(x => x.Age).First().Age; i < risk.First().Age; ++i)
                {
                    _calculatedRisk.Add(Double.NaN);
                }      

                foreach (var item in risk)
                {
                    _calculatedRisk.Add(item.AgeRisk);
                }

                NotifyOfPropertyChange(() => CalculatedRisk);
                NotifyOfPropertyChange(() => RiskCollection);


                return new LineSeries
                {
                    Values = _calculatedRisk,
                    Title = "Calculated Risk"
                };
            }
        }

        public LineSeries AverageRisk
        {
            get
            {
                if (_averageRisk != null && _averageRisk.Count > 0)
                {
                    return new LineSeries
                    {
                        Values = _averageRisk,
                        Title = "Average Risk"                        
                    };
                }

                var risk = _averageResultSet.ResultItems.OrderBy(x => x.Age);

                _averageRisk = new ChartValues<double>();

                foreach (var item in risk)
                {
                    _averageRisk.Add(item.AgeRisk);
                }

                NotifyOfPropertyChange(() => AverageRisk);
                NotifyOfPropertyChange(() => RiskCollection);


                return new LineSeries
                {
                    Values = _averageRisk,
                    Title = "Average Risk"                    
                };
            }
        }

        public List<string> Labels
        {
            get { return _averageResultSet.ResultItems.OrderBy(x => x.Age).Select(x => x.Age.ToString()).ToList(); }
        }

        public Func<double, string> YFormatter 
        {
            get { return value => value.ToString("F5", CultureInfo.InvariantCulture); }
        }
```

and my xaml code

```
        <lvc:CartesianChart Grid.Column="1" x:Name="RiskCollection" Series="{Binding RiskCollection}" MinWidth="300" Zoom="X" LegendLocation="Bottom" Margin="6,0" >
            <lvc:CartesianChart.AxisY>
                <lvc:Axis Title="Risk" x:Name="RiskLabel" LabelFormatter="{Binding YFormatter}">
                </lvc:Axis>
            </lvc:CartesianChart.AxisY>
            <lvc:CartesianChart.AxisX>
                <lvc:Axis Title="Age" x:Name="AgeLabel" Labels="{Binding Labels}" IsMerged="True">
                    <lvc:Axis.Separator>
                        <lvc:Separator StrokeThickness="0.5" StrokeDashArray="4" Step="5">
                            <lvc:Separator.Stroke>
                                <SolidColorBrush Color="#404F56" />
                            </lvc:Separator.Stroke>
                        </lvc:Separator>
                    </lvc:Axis.Separator>
                </lvc:Axis>
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>
```

I worked around this issue by using ObservablePoints and setting the x and y for each point, and not adding any without a value.

**Comment by beto-rodriguez** [comment]
@AndyConlisk  Thank you again for reporting, this really helps a lot.

I was trying to reproduce this error, but I was unable to, I think it got fixes with some previous commit

It would be awesome if you could try with 0.7.10 and let me know if the issue is solved, or if I am just not able to force it.

Thanks!

**Comment by AndyConlisk** [comment]
@beto-rodriguez I updated to 0.7.10 and the issue was solved. I was previously using 0.7.8

Thank you.
