### ISSUE TITLE
My code broke when I switched to Geared

### ISSUE THREAD

**Issue by w3sz** [beto-rodriguez/Live-Charts#520]
Hi,

I purchased Geared to get improved performance with large charts being updated every second.
I am running Windows 10 Pro with VS 2015, all updates done.  Windows version is Build 14393.s1_release_inmarket.170303-1614.
.NET Framework 4.5 
LiveCharts is v0.9.5
LiveCharts.Geared is v1.2.7
LiveCharts.WinForms is v0.9.5
LiveChartsWPF is v0.9.5

I am writing WinForms C# application.

My code before adding Geared worked fine except for bogging down when the number of displayed points became large.  The essential elements before adding Geared were:

using LiveCharts;
using LiveCharts.Defaults;
using LiveCharts.Wpf;
using LiveCharts.WinForms;
using LiveCharts.Geared;
using LiveCharts.Geared.Geometries;
using LiveCharts.Events;

        public ChartValues<ObservablePoint> dopplerPt { get; set; }
        public ChartValues<ObservablePoint> headingPt { get; set; }
        public ChartValues<ObservablePoint> speedPt { get; set; }
        public SeriesCollection dopplerPlots { get; set; }

   
            ChartValues<ObservablePoint> dopplerPt = new ChartValues<ObservablePoint>();
            ChartValues<ObservablePoint> headingPt = new ChartValues<ObservablePoint>();
            ChartValues<ObservablePoint> speedPt = new ChartValues<ObservablePoint>();

            System.Windows.Media.BrushConverter converter = new System.Windows.Media.BrushConverter();
            var brush = (System.Windows.Media.Brush)converter.ConvertFromString("#000000");
            if(brush.CanFreeze)
            {
                brush.Freeze();
            }
            Separator separator = new Separator();

            dopplerPlots = new SeriesCollection
            {
                new ScatterSeries
                {
                Title = "Doppler Shift",
                Values = dopplerPt,
                PointGeometry = DefaultGeometries.Diamond,
                MaxPointShapeDiameter =10,
                FontSize = 8,
                ScalesYAt = 0,
                Fill = brush
                },
                new ScatterSeries
                {
                Title = "Heading",
                Values = headingPt,
                PointGeometry = DefaultGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt = 1
                },
                new ScatterSeries
                {
                Title = "Speed",
                Values = speedPt,
                PointGeometry = DefaultGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt =2
                }
            };     

        
            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Hz",
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                LabelFormatter = value => ((Math.Abs(rateDopChange) <= 0.01) && (dopplerDataList.Count < 100)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.01) && (Math.Abs(rateDopChange) <= 0.02) && (dopplerDataList.Count < 50)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.02) && (Math.Abs(rateDopChange) <= 0.03) && (dopplerDataList.Count < 42)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.03) && (Math.Abs(rateDopChange) <= 0.04) && (dopplerDataList.Count < 34)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.04) && (Math.Abs(rateDopChange) <= 0.05) && (dopplerDataList.Count < 25)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.05) && (Math.Abs(rateDopChange) <= 0.1) && (dopplerDataList.Count < 20)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.1) && (Math.Abs(rateDopChange) <= 0.5) && (dopplerDataList.Count < 20)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.5) && (Math.Abs(rateDopChange) <= 1.0) && (dopplerDataList.Count < 10)) ? value.ToString("F2") :
                Math.Round(value).ToString(),
                Separator = new Separator
                {
                    Stroke = brush
                },
            });

            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "Degrees  (0 - 360)",
                ShowLabels = false,
                MaxValue = 370,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                },
            });
            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "km/h",
                MaxValue = 1300,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                }
            });
            dopGraph.AxisX.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Seconds",
                MinValue = 0,
                MinRange = 10,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    Stroke = brush
                }
            });

            dopGraph.Hoverable = false;
            dopGraph.DataTooltip = null;
            dopGraph.DisableAnimations = false;
            dopGraph.Series = dopplerPlots;
            dopGraph.LegendLocation = LegendLocation.Top;
            dopGraph.ForeColor = Color.Black;
            
                

                    foreach (var series in dopplerPlots)
                    {
                        if (series.Title == "Doppler Shift")
                        {
                            series.Values.Add(new ObservablePoint(iimandop, Doppler));
                        }
                        else if (series.Title == "Heading")
                        {
                            series.Values.Add(new ObservablePoint(iimandop, heading));
                        }
                        else if (series.Title == "Speed")
                        {
                            series.Values.Add(new ObservablePoint(iimandop, speed));
                        }
                    }
                    
                    
After Converting to Geared this became:

using LiveCharts;
using LiveCharts.Defaults;
using LiveCharts.Wpf;
using LiveCharts.WinForms;
using LiveCharts.Geared;
using LiveCharts.Geared.Geometries;
using LiveCharts.Events;

        public GearedValues<ObservablePoint> dopplerPt { get; set; }
        public GearedValues<ObservablePoint> headingPt { get; set; }
        public GearedValues<ObservablePoint> speedPt { get; set; }
        public SeriesCollection dopplerPlots { get; set; }

 
            GearedValues<ObservablePoint> dopplerPt = new GearedValues<ObservablePoint>();
            GearedValues<ObservablePoint> headingPt = new GearedValues<ObservablePoint>();
            GearedValues<ObservablePoint> speedPt = new GearedValues<ObservablePoint>();

            System.Windows.Media.BrushConverter converter = new System.Windows.Media.BrushConverter();
            var brush = (System.Windows.Media.Brush)converter.ConvertFromString("#000000");
            if(brush.CanFreeze)
            {
                brush.Freeze();
            }
            Separator separator = new Separator();

            dopplerPlots = new SeriesCollection
            {
                new GScatterSeries
                {
                Title = "Doppler Shift",
                Values = dopplerPt,
                GearedPointGeometry = GearedGeometries.Diamond,
                MaxPointShapeDiameter =10,
                FontSize = 8,
                ScalesYAt = 0,
                Fill = brush
                },
                new GScatterSeries
                {
                Title = "Heading",
                Values = headingPt,
                GearedPointGeometry = GearedGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt = 1
                },
                new GScatterSeries
                {
                Title = "Speed",
                Values = speedPt,
                GearedPointGeometry = GearedGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt =2
                }
            };

            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Hz",
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                LabelFormatter = value => ((Math.Abs(rateDopChange) <= 0.01) && (dopplerDataList.Count < 100)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.01) && (Math.Abs(rateDopChange) <= 0.02) && (dopplerDataList.Count < 50)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.02) && (Math.Abs(rateDopChange) <= 0.03) && (dopplerDataList.Count < 42)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.03) && (Math.Abs(rateDopChange) <= 0.04) && (dopplerDataList.Count < 34)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.04) && (Math.Abs(rateDopChange) <= 0.05) && (dopplerDataList.Count < 25)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.05) && (Math.Abs(rateDopChange) <= 0.1) && (dopplerDataList.Count < 20)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.1) && (Math.Abs(rateDopChange) <= 0.5) && (dopplerDataList.Count < 20)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.5) && (Math.Abs(rateDopChange) <= 1.0) && (dopplerDataList.Count < 10)) ? value.ToString("F2") :
                Math.Round(value).ToString(),
                Separator = new Separator
                {
                    Stroke = brush
                },
            });

            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "Degrees  (0 - 360)",
                ShowLabels = false,
                MaxValue = 370,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                },
            });
            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "km/h",
                MaxValue = 1300,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                }
            });
            dopGraph.AxisX.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Seconds",
                MinValue = 0,
                MinRange = 10,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    Stroke = brush
                }
            });

            dopGraph.Hoverable = false;
            dopGraph.DataTooltip = null;
            dopGraph.DisableAnimations = false;
            dopGraph.Series = dopplerPlots;
            dopGraph.LegendLocation = LegendLocation.Top;
            dopGraph.ForeColor = Color.Black;  

                    foreach (var series in dopplerPlots)
                    {
                        if (series.Title == "Doppler Shift")
                        {
                            series.Values.Add(new ObservablePoint(iimandop, Doppler));
                        }
                        else if (series.Title == "Heading")
                        {
                            series.Values.Add(new ObservablePoint(iimandop, heading));
                        }
                        else if (series.Title == "Speed")
                        {
                            series.Values.Add(new ObservablePoint(iimandop, speed));
                        }
                    }

This crashes with the error:
                 
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=LiveCharts.Geared
  StackTrace:
       at LiveCharts.Geared.GearedValues`1.e.b()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at LiveCharts.Geared.GearedValues`1.GetPoints(ISeriesView series)
       at l.d(Brush A_0, Brush A_1, Series A_2)
       at LiveCharts.Geared.GearedSeries.OnSeriesUpdateStart()
       at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force) in C:\Users\btord\Source\Repos\Live-Charts\Core40\ChartUpdater.cs:line 122
       at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView, Boolean force) in C:\Users\btord\Source\Repos\Live-Charts\WpfView\Components\ChartUpdater.cs:line 88
       at LiveCharts.Wpf.Components.ChartUpdater.OnTimerOnTick(Object sender, EventArgs args) in C:\Users\btord\Source\Repos\Live-Charts\WpfView\Components\ChartUpdater.cs:line 74
       at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Demo.WindowsForms.Program.Main() in E:\AirplaneScatter\AircraftScatter_2017_ThreadSafeNewGeared_TestOnly\Demo.WindowsForms\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Nothing has changed except for the code changes above.  I can't see what I am doing wrong...again, code worked fine before Geared was purchased and introduced into the code.
I get the same result using ObservablePoint or ScatterPoint.
I am sure it is something I don't understand in the changes needed when switching to geared, but I have been reading the source and Googling for info for 2 days and still can't figure it out so I am posting for help.
Thanks in advance for your help!
  

#### Extra notes

I would like to be able to use Geared.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>LiveCharts is v0.9.5
LiveCharts.Geared is v1.2.7
LiveCharts.WinForms is v0.9.5
LiveChartsWPF is v0.9.5</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>.NET Framework 4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 Pro with VS 2015, all updates done.  Windows version is Build 14393.s1_release_inmarket.170303-1614.</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi

I am sorry for the issue you are facing I created a repository tying to reproduce the error with the info you provided, and I was not able to get the exception, I think I the exception is not caused here.

In my opinion this exception could occur in the way you are updating the chart, specially in the next snippet:

    foreach (var series in dopplerPlots)
            {
                if (series.Title == "Doppler Shift")
                {
                    series.Values.Add(new ObservablePoint(9, 9));
                }
                else if (series.Title == "Heading")
                {
                    series.Values.Add(new ObservablePoint(8, 8));
                }
                else if (series.Title == "Speed")
                {
                    series.Values.Add(new ObservablePoint(7, 7));
                }
            }

Can I please now more about how you are calling this part of the code and how often you are?

Please see take a look at my repository and let me know what is the difference between your code, specially the way you are updating the data, notice I am only updating the data once, in the constructor of the `Window`
`

**Comment by beto-rodriguez** [comment]
The repo link:

https://github.com/beto-rodriguez/w3zsIssue

The interesting part:

https://github.com/beto-rodriguez/w3zsIssue/blob/master/Testing.Winforms/Form1.cs

**Comment by w3sz** [comment]
Hi Alberto,

Thanks for the quick response!  I still get the same error when I substitute in my program the code you used:

                series.Values.Add(new ObservablePoint(7, 7));

for my previous code:

       series.Values.Add(new ObservablePoint(totalsecs, Doppler));

These series.Values.Add statements are called by a Systems.Windows.Forms.timer once a second.

My code is overall complex but the path to the series.Value.Add is straightforward, being just the timer method with some if statements and calculations preceding the  series.Value.Add statements.  The series.Values.Add statements are within an extended "try" block but I don't think that should cause this issue..

Your w3szIssue code runs fine here when I run it as a separate project, even when I add in all of the references and using namespace declarations that I used in my project.  But if I add a button to the form, even if it does nothing, then your code fails again at line 122 of ChartUpdater.cs, but this time with an out of memory error:
System.OutOfMemoryException was unhandled
  HResult=-2147024882
  Message=Exception of type 'System.OutOfMemoryException' was thrown.
  Source=LiveCharts.Geared
  StackTrace:
       at LiveCharts.Geared.GearedValues`1.e.b()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at LiveCharts.Geared.GearedValues`1.GetPoints(ISeriesView series)
       at l.d(Brush A_0, Brush A_1, Series A_2)
       at LiveCharts.Geared.GearedSeries.OnSeriesUpdateStart()
       at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations, Boolean force) in C:\Users\btord\Source\Repos\Live-Charts\Core40\ChartUpdater.cs:line 122

I must say that I did not realize that the series.Values.Add statement was only supposed to be called once, and I was calling it every second.  

So I have changed my code to:

using LiveCharts;
using LiveCharts.Defaults;
using LiveCharts.Geared;
using LiveCharts.Geared.Geometries;
using LiveCharts.Wpf;
//.......................

        public GearedValues<ObservablePoint> dopplerPt { get; set; }
        public GearedValues<ObservablePoint> headingPt { get; set; }
        public GearedValues<ObservablePoint> speedPt { get; set; }
        public SeriesCollection dopplerPlots { get; set; }
//...........................

            dopplerPt = new GearedValues<ObservablePoint>();
            headingPt = new GearedValues<ObservablePoint>();
            speedPt = new GearedValues<ObservablePoint>();

            System.Windows.Media.BrushConverter converter = new System.Windows.Media.BrushConverter();
            var brush = (System.Windows.Media.Brush)converter.ConvertFromString("#000000");
            if(brush.CanFreeze)
            {
                brush.Freeze();
            }
            Separator separator = new Separator();

            dopplerPlots = new SeriesCollection
            {
                new GScatterSeries
                {
                Title = "Doppler Shift",
                Values = dopplerPt,
                GearedPointGeometry = GearedGeometries.Diamond,
                MaxPointShapeDiameter =10,
                FontSize = 8,
                ScalesYAt = 0,
                Fill = brush
                },
                new GScatterSeries
                {
                Title = "Heading",
                Values = headingPt,
                GearedPointGeometry = GearedGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt = 1
                },
                new GScatterSeries
                {
                Title = "Speed",
                Values = speedPt,
                GearedPointGeometry = GearedGeometries.Diamond,
                MaxPointShapeDiameter = 8,
                FontSize = 8,
                ScalesYAt =2
                }
            };

            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Hz",
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
       //         LabelFormatter = value => ((Math.Abs(rateDopChange) <= 0.5) && (dopplerPlots.Count < 100)) ? value.ToString("F2") : Math.Round(value).ToString(),
                LabelFormatter = value => ((Math.Abs(rateDopChange) <= 0.01) && (dopplerPlots.Count < 100)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.01) && (Math.Abs(rateDopChange) <= 0.02) && (dopplerPlots.Count < 50)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.02) && (Math.Abs(rateDopChange) <= 0.03) && (dopplerPlots.Count < 42)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.03) && (Math.Abs(rateDopChange) <= 0.04) && (dopplerPlots.Count < 34)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.04) && (Math.Abs(rateDopChange) <= 0.05) && (dopplerPlots.Count < 25)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.05) && (Math.Abs(rateDopChange) <= 0.1) && (dopplerPlots.Count < 20)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.1) && (Math.Abs(rateDopChange) <= 0.5) && (dopplerPlots.Count < 20)) ? value.ToString("F2") :
                ((Math.Abs(rateDopChange) > 0.5) && (Math.Abs(rateDopChange) <= 1.0) && (dopplerPlots.Count < 10)) ? value.ToString("F2") :
                Math.Round(value).ToString(), 
               Separator = new Separator
                {
                    Stroke = brush
                },
            });

            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "Degrees  (0 - 360)",
                ShowLabels = false,
                MaxValue = 370,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                },
            });
            dopGraph.AxisY.Add(new Axis
            {
                Position = AxisPosition.RightTop,
                Title = "km/h",
                MaxValue = 1300,
                MinValue = 0,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    IsEnabled = false
                }
            });
            dopGraph.AxisX.Add(new Axis
            {
                Position = AxisPosition.LeftBottom,
                Title = "Seconds",
                MinValue = double.NaN,
                MinRange = 10,
                Foreground = brush,
                FontWeight = System.Windows.FontWeights.Bold,
                FontSize = 15,
                Separator = new Separator
                {
                    Stroke = brush
                }
            });

            dopGraph.Hoverable = false;
            dopGraph.DataTooltip = null;
            dopGraph.DisableAnimations = false;
            dopGraph.Series = dopplerPlots;
            dopGraph.LegendLocation = LegendLocation.Top;
//...........................................
and the timer click each second just runs:
                        dopplerPt.Add(new ObservablePoint(totalsecs, Doppler));
                        speedPt.Add(new ObservablePoint(totalsecs, speed));
                        headingPt.Add(new ObservablePoint(totalsecs, heading));

I still get the out of range error at line 122 of ChartUpdater.cs.

I hope that the above sheds some light on things.

Thanks again, Alberto!

**Comment by beto-rodriguez** [comment]
I am really sorry for the issue you are facing, In my opinion this seems an issue from my side, I will try to reproduce, please feel free to mail me at support@lvcharts.net I can try to debug your code with you, if you agree.

I'll try to repro and let you know.

Again I am really sorry for the issue. I keep investigating, will be back with more info.

**Comment by w3sz** [comment]
Thanks, Alberto!  You are great :)
My code is more than 11,750 lines;  so I will make a small program from the relevant parts of the code which are a tiny fraction of the whole and test it here to make sure it fails in the same way as the whole package.  Then I will send it to you.  Is it OK to send it as a zip to your email address support@lvcharts.net?

Thanks again, Alberto!  I really appreciate your helpfulness, and LiveCharts is great too!

**Comment by beto-rodriguez** [comment]
The zip would help a lot, thanks!
