### ISSUE TITLE
Element is already the child of another element

### ISSUE THREAD

**Issue by taivasverkko** [beto-rodriguez/Live-Charts#547]
When navigating to a page second time I get following error :
System.Runtime.InteropServices.COMException: No installed components were detected. 
Element is already the child of another element. at System.Runtime.InteropServices.WindowsRuntime.IVector`1.Append(T value) at System.Runtime.InteropServices.WindowsRuntime.VectorToCollectionAdapter.Add[T](T item) at LiveCharts.Uwp.Charts.Base.Chart.AddToView(Object element) at LiveCharts.Uwp.Charts.Base.Chart.EnsureElementBelongsToCurrentView(Object element) at LiveCharts.ChartUpdater.InitializeSeries

Using Livechart.UWP v.0.8.0

**Comment by beto-rodriguez** [comment]
This is a limitation in the design of LiveCharts, I am updating the docs, it will include limitations.

you are probably adding the same series in both different charts, instead use the same ChartValues instance for 2 different series.

you are probably doing:

    var series = new LineSeries{Values = new ChartValues};
    var chart1 = new CartesianChart { Series = new SeriesCollection { series } };
    var chart2 = new CartesianChart { Series = new SeriesCollection { series } };

What you can do is:

    var values = new ChartValues<T>();
    var chart1 = new CartesianChart { Series = new SeriesCollection { new LineSeries{ Values = values} } };
    var chart2 = new CartesianChart { Series = new SeriesCollection { new LineSeries{ Values = values} } };

**Comment by taivasverkko** [comment]
I have only one series that is binded to one chart. 

XAML : 
```
 <lvc:CartesianChart x:Name="TransactionsChart"  Series="{Binding TransactionSeries}" LegendLocation="None" Height="300">
            <lvc:CartesianChart.AxisX>
                <lvc:Axis Title="Month" Labels="{Binding TransactionSeriesLabels}" />
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>
```

Viewmodel :
```
  public SeriesCollection TransactionSeries
        {
            get
            {
                return _TransactionSeries;
            }
            set { Set(ref _TransactionSeries, value); }
        }
```

**Comment by brianstull** [comment]
Has there been any work on this problem? I'm running into what looks like the same issue. In my case, I have a model which holds the SeriesCollection for a CartesianChart. The model is bound to a Page and if the page gets reloaded it throws the following:

System.Runtime.InteropServices.COMException: No installed components were detected.
Element is already the child of another element.
   at System.Runtime.InteropServices.WindowsRuntime.IVector`1.Append(T value)
   at System.Runtime.InteropServices.WindowsRuntime.VectorToCollectionAdapter.Add[T](T item)
   at LiveCharts.Uwp.Charts.Base.Chart.AddToView(Object element)
   at LiveCharts.Uwp.Charts.Base.Chart.EnsureElementBelongsToCurrentView(Object element)
   at LiveCharts.ChartUpdater.Update(Boolean r

This is preventing me from using the chart in an MVVM application. 

Same version as previous poster: UWP 0.8.0

Thanks.

**Comment by bidasknakayama** [comment]
When will you update / fix this issue ?
v 0.8.0 has still this problem.

**Comment by Dima-dima** [comment]
Hello, use Uwp 0.8.0, and have the same problem (Element is already the child of another element) while try bind to SeriesCollection.

  <lvc:CartesianChart x:Name="chartPanel"                                
                                Visibility="Collapsed"                                
                                Series="{x:Bind SeriesCollection,Mode=OneWay}"                                
                                HorizontalAlignment="Left">

Please, need any issue
