### ISSUE TITLE
Changing tabs intermittently throws exception

### ISSUE THREAD

**Issue by kpnz** [beto-rodriguez/Live-Charts#549]
#### How to reproduce?

https://bitbucket.org/Veriphi/graphbug/

Pressing the buttons on the left rapidly should throw an exception very similar to the one I am experiencing.

It should plot a graph on startup also.

#### Extra notes

```
   at LiveCharts.Geared.GearedValues`1.e.b()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LiveCharts.Geared.GearedValues`1.GetPoints(ISeriesView series)
   at LiveCharts.Geared.GearedSeries.a(Boolean A_0)
   at LiveCharts.Geared.GearedSeries.Erase(Boolean removeFromView)
   at LiveCharts.Wpf.Charts.Base.Chart.OnSeriesChanged(DependencyObject o, DependencyPropertyChangedEventArgs e) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Charts\Base\Chart.cs:line 169
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
   at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.TreeWalkHelper.OnInheritablePropertyChanged(DependencyObject d, InheritablePropertyChangeInfo info, Boolean visitedViaVisualTree)
```

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>LiveCharts.Wpf v0.9.6</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Extra notes:

> System.IndexOutOfRangeException occurred
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=<Cannot evaluate the exception source>

Notice I've seen this errors before, the library was thread safe.

This normally happens when ChartValues goes out of sync.

If you are updating the chart from multiple threads, its is important to keep your chart values safe, since 0.9.3, I made ChartValues thread safe (at least for most cases) but you must help the library to (I know this needs to be documented, I am reviewing all the docs right now...)

Here is a sample that does update the chart from multiple threads in a short period of time. I ran this for at least 20 hours without any exception (with 8 Tasks).

https://lvcharts.net/App/examples/v1/wpf/Constant%20Changes%20II

Notice the note:

> //when multi threading avoid indexed calls like -> Values[0] 
                    //instead enumerate the collection
                    //ChartValues/GearedValues returns a thread safe copy once you enumerate it.
                    //TIPS: use foreach instead of for
                    //LINQ methods also enumerate the collections

**Comment by kpnz** [comment]
Yes, I suspect it is a threading issue.

I don't make any calls like `Values[0]` but I do this sort of thing as I have a dynamic number of series:

```
 for (int i = 0; i < foo.Count; i++)
 {
   TempSeriesCollection[i].Values.Add(new TimePoint(DateTime.Now, foo[i].Temperature));
 }
```
Is this ok?

**Comment by kpnz** [comment]
Ok I found where it happens. It's when I set a SeriesCollection property to a new SeriesCollection instance. 

```
private SeriesCollection currentDataSeries;
public SeriesCollection CurrentDataSeries
{
  get
  {
    return currentDataSeries;
  }
  private set
  {
    SetProperty(ref currentDataSeries, value);
  }
}

private void TestController_TestComplete(object sender, EventArgs e)
{
  Application.Current.Dispatcher.Invoke(() => UpdateGraph());
}


private void UpdateGraph()
{
  CurrentDataSeries = graphGenerator.GenerateGraph();
}
```

**Comment by kpnz** [comment]
How does geared values function differently to the chart values? I swapped the geared library for the source code on your repository in an attempt to get more debugging information, but I can't get it to throw the exception with the standard library.

**Comment by beto-rodriguez** [comment]
Thanks for the project you created, I was able to identify and fix the issue,  it will be included in the next release of the library, should be published this weekend.

**Comment by kpnz** [comment]
Awesome, that will help a lot! Cheers
