### ISSUE TITLE
UWP App example & library for UWP are broken

### ISSUE THREAD

**Issue by RikardoPons** [beto-rodriguez/Live-Charts#567]
#### How to reproduce?

Just download lastest version 0.9.6 upgrade the UWP projects, compile and execute. 

*Explain what you expect, feedback, images or anything you consider necessary*

I navigate in the examples and I have many crashes with labels and series from the library

<table>
<tr>
    <td>Live-0.9.6</td>
    <td>*your Live-Charts version here*</td>
</tr>
<tr>
    <td>UWP 15063</td>
    <td>15063</td>
</tr>
<tr>
    <td>Windows</td>
    <td>1703</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
You are right, it will be updated soon.

**Comment by tesar-tech** [comment]
It is still (or again?) broken for uwp. Just running the sample chart throws this error on build: 


> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\user\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.	lctest	

Error file contains this: 

> UNHANDLED EXCEPTIONS FROM PROCESS 46960:
> 25.03.2020 17:43:09
> System.IO.IOException: Pipe is broken.
>    at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
>    at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
>    at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)

Windows 1903; UWP 18362

 Any news about future plan?
