### ISSUE TITLE
An unhandled exception of type 'System.InvalidOperationException' occurred in PresentationCore.dll

### ISSUE THREAD

**Issue by lonewolf9277** [beto-rodriguez/Live-Charts#606]
Hi, I just made a new project and dragged a cartesian chart on a form. When I run the project this error comes up:
An unhandled exception of type 'System.InvalidOperationException' occurred in PresentationCore.dll on 
`this.cartesianChart1 = new LiveCharts.WinForms.CartesianChart();` in Form.Designer.cs.
Any way to fix this?

Details:
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The calling thread must be STA, because many UI components require this.
  Source=PresentationCore
  StackTrace:
       at System.Windows.Input.InputManager..ctor()
       at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
       at System.Windows.Input.KeyboardNavigation..ctor()
       at System.Windows.FrameworkElement.FrameworkServices..ctor()
       at System.Windows.FrameworkElement.EnsureFrameworkServices()
       at System.Windows.FrameworkElement..ctor()
       at System.Windows.Controls.Control..ctor()
       at System.Windows.Controls.UserControl..ctor()
       at LiveCharts.Wpf.Charts.Base.Chart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Charts\Base\Chart.cs:line 63
       at LiveCharts.Wpf.CartesianChart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\CartesianChart.cs:line 40
       at LiveCharts.WinForms.CartesianChart..ctor() in c:\Users\btord\Documents\Projects\LiveCharts\WinFormsView\CartesianChart.cs:line 46
       at LiveCharts.Form2.InitializeComponent() in c:\Users\DELL\Documents\Visual Studio 2013\Projects\LiveCharts\LiveCharts\Form2.Designer.cs:line 31
       at LiveCharts.Form2..ctor() in c:\Users\DELL\Documents\Visual Studio 2013\Projects\LiveCharts\LiveCharts\Form2.cs:line 20
       at LiveCharts.Program.Main() in c:\Users\DELL\Documents\Visual Studio 2013\Projects\LiveCharts\LiveCharts\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
did you installed the package from Nuget?

It seems that you are missing some references.

**Comment by lonewolf9277** [comment]
Yes I added it from Nuget. I followed the tutorial.

**Comment by beto-rodriguez** [comment]
I am not sure what could be wrong in your case, ensure all the dependencies are installed correctly.

I am closing this for now, feel free to reply this, or create a new issue if necessary.
