### ISSUE TITLE
AnimationException when zoomin in a chart containing a LogarithmicAxis

### ISSUE THREAD

**Issue by starnutoditopo** [beto-rodriguez/Live-Charts#626]
#### How to reproduce?

Here's a simple window containing a (zoomable) CartesianChart with a series and a LogarithmicAxis:

```
<Window x:Class="VisualElement.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:lvc="clr-namespace:LiveCharts.Wpf;assembly=LiveCharts.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <lvc:CartesianChart
        LegendLocation="Top"
        Zoom="Xy"
        >
        <lvc:CartesianChart.Series>
            <lvc:LineSeries Title="Sample">
                <lvc:LineSeries.Values>1,2,3,2,3,4,3,4</lvc:LineSeries.Values>
            </lvc:LineSeries>
        </lvc:CartesianChart.Series>
        <lvc:CartesianChart.AxisY>
            <lvc:LogarithmicAxis
                Title="Value (logarithmic)"
                Position="RightTop"
            />
        </lvc:CartesianChart.AxisY>
    </lvc:CartesianChart>
</Window>

```
Code-behind is just the default for a new project: 

```
namespace VisualElement
{
    public partial class MainWindow
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
}

```

At run-time, when the wheel is scrolled to zoom in, the following error occurs:

```
Type: System.Windows.Media.Animation.AnimationException
Message: Cannot animate the 'Top' property on a 'System.Windows.Controls.TextBlock' using a 'System.Windows.Media.Animation.DoubleAnimation'. For details see the inner exception.
Stack trace:    at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner exception:
    Type: System.InvalidOperationException
    Message: 'System.Windows.Media.Animation.DoubleAnimation' cannot use default origin value of 'NaN'.
    Stack trace:    at System.Windows.Media.Animation.DoubleAnimation.GetCurrentValueCore(Double defaultOriginValue, Double defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.DoubleAnimationBase.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.AnimationStorage.GetCurrentPropertyValue(AnimationStorage storage, DependencyObject d, DependencyProperty dp, PropertyMetadata metadata, Object baseValue)
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
    Inner exception:
```

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7.0 (WPF)</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>v4.0.30319</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Microsoft Windows [Version 10.0.15063]</td>
</tr>
</table>

**Comment by utkarshnyu** [comment]
I encountered the same problem, Did you ever find a fix ?

Throws: Double Animation error!

**Comment by FireBlaze9311** [comment]
I had the same problem. Fixed it with `DisableAnimations="True"`.
