### ISSUE TITLE
Destination array was not long enough

### ISSUE THREAD

**Issue by laszlopaszternak** [beto-rodriguez/Live-Charts#637]
#### How to reproduce?

I have absolutely no idea how this can be reproduced, but sometimes we get this error:

2017-09-21 18:58:45,781 ERROR Application.Wpf.App.CurrentDomain_UnhandledException *****   Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
2017-09-21 18:58:45,826 ERROR Application.Wpf.App.CurrentDomain_UnhandledException *****    at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at LiveCharts.Helpers.NoisyCollection`1.CopyTo(T[] array, Int32 index) in C:\Users\btord\Source\Repos\Live-Charts\Core40\Helpers\NoisyCollection.cs:line 532
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at REMOVED
   at LiveCharts.Configurations.CartesianMapper`1.Evaluate(Int32 key, T value, ChartPoint point) in C:\Users\btord\Source\Repos\Live-Charts\Core40\Configurations\CartesianMapper.cs:line 47
   at LiveCharts.ChartValues`1.<GetPoints>d__11.MoveNext() in C:\Users\btord\Source\Repos\Live-Charts\Core40\ChartValues.cs:line 203
   at LiveCharts.Helpers.Extentions.ForEach[T](IEnumerable`1 source, Action`1 predicate) in C:\Users\btord\Source\Repos\Live-Charts\Core40\Helpers\Extentions.cs:line 43
   at LiveCharts.Wpf.Series.OnValuesInstanceChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs) in C:\Users\btord\Source\Repos\Live-Charts\WpfView\Series.cs:line 540

#### Extra notes

I found that this error had appeared previously in the buglist (https://github.com/beto-rodriguez/Live-Charts/issues/336) but it's marked as fixed as of version 0.9.3. Unfortunately I was using 0.9.5 when I encountered the problem...

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.5.</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6</td>
</tr>
<tr>
    <td>Windows</td>
    <td>W10 Enterprise (V1703)</td>
</tr>
</table>

**Comment by JithendarAnandan** [comment]
I have run into the same issue with v0.9.7. Is there a workaround for this?

**Comment by nadim-241** [comment]
Don't suppose anyone has a fix for this yet? Currently updating a chart from another thread every 50ms breaks everything

**Comment by beto-rodriguez** [comment]
You must invoke the data changes in the UI threa.
