### ISSUE TITLE
Code Break When binding multiple values to Angular Gauge

### ISSUE THREAD

**Issue by Cossmin** [beto-rodriguez/Live-Charts#643]
I am trying to bind all the values in the Gauge to my ViewModel. There's no problem with my queries because it works perfectly for text boxes and it works for the Gauge except for the first line starting from 0. If however I replace it with a static value and reference it in the next line, it works, it's really strange.
I've been spending days trying to get it to work and I'm 98% there. Please help!

<lvc:AngularSection FromValue="0" ToValue="{Binding CarsInspectedGoalsRed}" Fill="#dd5143"/>

#### XAML
```
<lvc:AngularGauge Value="{Binding CarsInspected}" FromValue="0" Grid.Column="0" Grid.Row="2" ToValue="{Binding CarsInspectedGoalsGreen}"
      Wedge="300"
      TicksForeground="White" Foreground="WhiteSmoke" 
      FontWeight="Bold" FontSize="16"
      SectionsInnerRadius=".6" Margin="0" MinWidth="300">
    <lvc:AngularGauge.Sections>
        <lvc:AngularSection FromValue="0" ToValue="{Binding CarsInspectedGoalsRed}" Fill="#dd5143"/>
        <lvc:AngularSection FromValue="{Binding CarsInspectedGoalsRed}" ToValue="{Binding CarsInspectedGoalsGreen}" Fill="#7cb82f"/>
    </lvc:AngularGauge.Sections>
</lvc:AngularGauge>

```
#### ViewModel

```
namespace Location.ViewModel
{
    public class LocationViewModel : INotifyPropertyChanged
    {

        public LocationViewModel()
        {
            SetBusinessDays();
            SetHolidays();
            SetWorkingDays();
            SetCarsInspectedGoal();
            SetCarsInspectedGoalRed();
            SetCarsInspectedGoalYellow();
            SetCarsInspectedGoalGreen();

        }

        public DateTime mDate = DateTime.Now;


        public DateTime MDate
        {
            
            get { return mDate; }
            set
            {
                if (value == mDate)
                {
                    return;
                }
                else if (_selectedTabIndex == 0)
                {
                    mDate = value;
                }

                else
                {
                    mDate = value;
                    OnPropertyChanged("MDate");
                    SetBusinessDays();
                    SetHolidays();
                    SetWorkingDays();
                    SetCarsInspectedGoal();
                    SetCarsInspectedGoalRed();
                    SetCarsInspectedGoalYellow();
                    SetCarsInspectedGoalGreen();
                }

            }

        }

double _carsInspectedGoals;

public double CarsInspectedGoals
{
    get { return _carsInspectedGoals; }
    set
    {
        _carsInspectedGoals = value;
        OnPropertyChanged("CarsInspectedGoals");
    }
}

double _carsInspectedGoalsRed;

public double CarsInspectedGoalsRed
{
    get { return _carsInspectedGoalsRed; }
    set
    {
        _carsInspectedGoalsRed = value;
        OnPropertyChanged("CarsInspectedGoalsRed");
    }
}

double _carsInspectedGoalsYellow;

public double CarsInspectedGoalsYellow
{
    get { return _carsInspectedGoalsYellow; }
    set
    {
        _carsInspectedGoalsYellow = value;
        OnPropertyChanged("CarsInspectedGoalsYellow");
    }
}

double _carsInspectedGoalsGreen;

public double CarsInspectedGoalsGreen
{
    get { return _carsInspectedGoalsGreen; }
    set
    {
        _carsInspectedGoalsGreen = value;
        OnPropertyChanged("CarsInspectedGoalsGreen");
    }
}

private void SetCarsInspectedGoal()
{
    int.TryParse(MDate.ToString("MM"), out int month);
    CarsInspectedGoals = Convert.ToDouble(db.Targets.Where(a => (a.Description == "CarsInspected") && (a.sMonth == month) && (a.Location == "Aberdeen")).Select(a => a.Target1).FirstOrDefault());
}

private void SetCarsInspectedGoalRed()
{
    int.TryParse(MDate.ToString("MM"), out int month);
    if (WorkingDays != 0)
    {
    CarsInspectedGoalsRed = CarsInspectedGoals * Convert.ToDouble(db.Targets.Where(a => (a.sMonth == month) && (a.Location == "Aberdeen") && (a.Description == "CarsInspected")).Select(a => a.Red).FirstOrDefault()) / WorkingDays * DaysCompleted;
    }
    else
    {
        return;
    }
    
}

private void SetCarsInspectedGoalYellow()
{
    int.TryParse(MDate.ToString("MM"), out int month);
    if (WorkingDays != 0)
    {
    CarsInspectedGoalsYellow = CarsInspectedGoals * Convert.ToDouble(db.Targets.Where(a => (a.sMonth == month) && (a.Location == "Aberdeen") && (a.Description == "CarsInspected")).Select(a => a.Yellow).FirstOrDefault()) / WorkingDays * DaysCompleted;
    }
    else
    {
        return;
    }
   
}

private void SetCarsInspectedGoalGreen()
{
    if (WorkingDays != 0)
    {
        CarsInspectedGoalsGreen = CarsInspectedGoals / WorkingDays * DaysCompleted;
    }
    else
    {
        return;
    }

}

private void SetHolidays()
{
    int.TryParse(MDate.ToString("MM"), out int month);
    HolidaysInMonth = db.Holidays.Where(a => (a.Date <= MDate) && (a.Date.Month) == month).Select(a => a.ID).Count();
}


private void SetBusinessDays()

{
    BusinessDays = Enumerable.Range(1, DateTime.DaysInMonth(MDate.Year, MDate.Month))
                         .Select(day => new DateTime(MDate.Year, MDate.Month, day))
                         .Count(d => d.DayOfWeek != DayOfWeek.Sunday &&
                                     d.DayOfWeek != DayOfWeek.Saturday);
}

private void SetWorkingDays()
{
    int.TryParse(MDate.ToString("MM"), out int month);
    WorkingDays = (BusinessDays - HolidaysInMonth);
}

```
ERROR:

> System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>HRSX-Aberdeen.exe</AppDomain><Exception><ExceptionType>System.Collections.Generic.KeyNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The given key was not present in the dictionary.</Message><StackTrace>   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at LiveCharts.Wpf.AngularGauge.UpdateSections() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularGauge.cs:line 488
>    at LiveCharts.Wpf.AngularSection.Redraw(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularSection.cs:line 97
>    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry&amp;amp; newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
>    at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
>    at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
>    at System.Windows.Data.BindingExpression.Activate(Object item)
>    at System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
>    at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
>    at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
>    at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry&amp;amp; newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperty(TreeChangeInfo info, DependencyObject d, FrameworkObject&amp;amp; fo, DependencyProperty dp, FrameworkPropertyMetadata fMetadata, Style selfStyle, Style selfThemeStyle, ChildRecord&amp;amp; childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
>    at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperties(TreeChangeInfo info, FrameworkElement fe, FrameworkContentElement fce, Style selfStyle, Style selfThemeStyle, ChildRecord&amp;amp; childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
>    at System.Windows.FrameworkElement.InvalidateTreeDependentProperties(TreeChangeInfo parentTreeState, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
>    at System.Windows.FrameworkElement.OnAncestorChangedInternal(TreeChangeInfo parentTreeState)
>    at System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
>    at System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
>    at System.Windows.FrameworkElement.AddLogicalChild(Object child)
>    at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
>    at System.Windows.Controls.UIElementCollection.Add(UIElement element)
>    at LiveCharts.Wpf.AngularGauge.Draw() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularGauge.cs:line 398
>    at LiveCharts.Wpf.AngularGauge.&amp;lt;.ctor&amp;gt;b__6(Object sender, SizeChangedEventArgs args) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularGauge.cs:line 85
>    at System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
>    at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
>    at System.Windows.ContextLayoutManager.UpdateLayout()
>    at System.Windows.UIElement.UpdateLayout()
>    at System.Windows.Controls.TabItem.OnPreviewGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
>    at System.Windows.UIElement.OnPreviewGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
>    at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
>    at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
>    at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
>    at System.Windows.UIElement.Focus()
>    at System.Windows.Controls.TabItem.SetFocus()
>    at System.Windows.Controls.TabItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
>    at System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp;amp; msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run(Window window)
>    at System.Windows.Application.Run()
>    at HRSX_Aberdeen.App.Main()</StackTrace><ExceptionString>System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at LiveCharts.Wpf.AngularGauge.UpdateSections() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularGauge.cs:line 488
>    at LiveCharts.Wpf.AngularSection.Redraw(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularSection.cs:line 97
>    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry&amp;amp; newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
>    at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
>    at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
>    at System.Windows.Data.BindingExpression.Activate(Object item)
>    at System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
>    at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
>    at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
>    at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry&amp;amp; newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperty(TreeChangeInfo info, DependencyObject d, FrameworkObject&amp;amp; fo, DependencyProperty dp, FrameworkPropertyMetadata fMetadata, Style selfStyle, Style selfThemeStyle, ChildRecord&amp;amp; childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
>    at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperties(TreeChangeInfo info, FrameworkElement fe, FrameworkContentElement fce, Style selfStyle, Style selfThemeStyle, ChildRecord&amp;amp; childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
>    at System.Windows.FrameworkElement.InvalidateTreeDependentProperties(TreeChangeInfo parentTreeState, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
>    at System.Windows.FrameworkElement.OnAncestorChangedInternal(TreeChangeInfo parentTreeState)
>    at System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
>    at System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
>    at System.Windows.FrameworkElement.AddLogicalChild(Object child)
>    at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
>    at System.Windows.Controls.UIElementCollection.Add(UIElement element)
>    at LiveCharts.Wpf.AngularGauge.Draw() in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularGauge.cs:line 398
>    at LiveCharts.Wpf.AngularGauge.&amp;lt;.ctor&amp;gt;b__6(Object sender, SizeChangedEventArgs args) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\AngularGauge.cs:line 85
>    at System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
>    at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
>    at System.Windows.ContextLayoutManager.UpdateLayout()
>    at System.Windows.UIElement.UpdateLayout()
>    at System.Windows.Controls.TabItem.OnPreviewGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
>    at System.Windows.UIElement.OnPreviewGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
>    at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
>    at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
>    at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
>    at System.Windows.UIElement.Focus()
>    at System.Windows.Controls.TabItem.SetFocus()
>    at System.Windows.Controls.TabItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
>    at System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp;amp; msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run(Window window)
>    at System.Windows.Application.Run()

**Comment by gtaspider** [comment]
got the same problem when I use bindings on the  From/ToValue of AngularSection

**Comment by TeamTracer** [comment]
I also have the same, is there any solution to this?

**Comment by Verryan** [comment]
I got the same problem and I solve it.

I download the source and I modify the source like this :
In AngularGauge line 385, I write this :
`
foreach (var section in Sections)
 {
                   PieSlice slice;

    section.Owner = this;

    if (!Slices.TryGetValue(section, out slice))
    {
        slice = new PieSlice();
        Slices[section] = slice;
    }
}

foreach (var section in Sections)
{
    var slice = Slices[section];

    var p = (Canvas)section.Parent;
    if (p != null) p.Children.Remove(section);
    Canvas.Children.Add(section);
    var ps = (Canvas)slice.Parent;
    if (ps != null) ps.Children.Remove(slice);
    Canvas.Children.Add(slice);
}
`

@beto-rodriguez , 
I'm new to git. Can you verify and merge this code ?

**Comment by ElBonds** [comment]
I get this same problem. Will there be a fix in the next release? I'm currently using the LiveCharts and LiveCharts.Wpf NuGets that say they are version 0.9.7.
