### ISSUE TITLE
Geared Toolkit crashes when mouse hovered over graph.

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [beto-rodriguez/Live-Charts#733]
#### How to reproduce?

*
I was using the normal charting functions and loving it.  I just upgraded to Geared.  Now it crashes when I move my mouse over the graph.  I'm sure it's some sort of tooltip issue.

            <wpf:CartesianChart Grid.Row="1">
                <wpf:CartesianChart.Series>
                    <geared:GLineSeries Values="{Binding Financial}" x:Name="LineSeries"  PointGeometrySize="5" LineSmoothness="1" StrokeThickness="2" Stroke="Black" />
                    <geared:GOhlcSeries Values="{Binding Financial}" x:Name="OhlcSeries"/>
                    <geared:GScatterSeries Values="{Binding BreakoutHigh}" x:Name="BreakoutHigh" PointGeometry="{x:Static wpf:DefaultGeometries.Triangle}" Stroke="Green" StrokeThickness="2" />
                    <geared:GScatterSeries Values="{Binding BreakoutLow}" x:Name="BreakoutLow" PointGeometry="{x:Static wpf:DefaultGeometries.Cross}" Stroke="Purple" StrokeThickness="2"  /> 
                </wpf:CartesianChart.Series>
                <wpf:CartesianChart.AxisY>
                    <wpf:Axis Width="100" Title="Price" LabelFormatter="{Binding PriceFormatter}" Position="RightTop"></wpf:Axis>
                </wpf:CartesianChart.AxisY>
            </wpf:CartesianChart>
            <wpf:CartesianChart Grid.Row="2">
                <wpf:CartesianChart.Series>
                    <wpf:ColumnSeries Values="{Binding Volume}" x:Name="VolumeSeries" />
                </wpf:CartesianChart.Series>
                <wpf:CartesianChart.AxisY>
                    <wpf:Axis Width="100" Title="Volume" LabelFormatter="{Binding VolumeFormatter}" Position="RightTop"></wpf:Axis>
                </wpf:CartesianChart.AxisY>
            </wpf:CartesianChart>

I tried to set the tooltip to null, but the error still occurs.

 <wpf:CartesianChart Grid.Row="1" DataTooltip="{x:Null}">
*

#### Extra notes

*Dispatcher Unhandled Exception
System.NullReferenceException
Object reference not set to an instance of an object.

   at LiveCharts.Geared.GearedValues`1.a.b(ChartPoint A_0)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LiveCharts.Geared.GearedValues`1.a(Chart A_0, Point A_1)
   at LiveCharts.Geared.GearedValues`1.a(Object A_0, MouseEventArgs A_1)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*1.2.8.2*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*.NET Framework 4.6.1*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*Windows 10*</td>
</tr>
</table>

**Comment by ZombiesWithCoffee** [comment]
I see my error.  I had forgotten to upgrade my other chart to geared. 

         <wpf:ColumnSeries Values="{Binding Volume}" x:Name="VolumeSeries" />

I'm not sure why that would case a mouse error though.

**Comment by mascatul** [comment]
Was this fixed ? I tried the trial but still crash on mouse hoover

**Comment by derobojo** [comment]
I am having this issue as well and I have not been able to find a solution

**Comment by ZombiesWithCoffee** [comment]
There's no solution for it, but you can cheat!

App.xaml

     <Application x:Class="AlphaSigma.Binance.App"
             DispatcherUnhandledException="Application_DispatcherUnhandledException" 

App.xaml.cs

        void Application_DispatcherUnhandledException(object sender, DispatcherUnhandledExceptionEventArgs e)
        {
            if (e.Exception.StackTrace.StartsWith("   at LiveCharts.Geared.GearedValues`1.e.b()"))
            {
                e.Handled = true;
                return;
            }

**Comment by mattanti** [comment]
@ZombiesWithCoffee Have you found a different solution by now? Or is this still the only way?

**Comment by sergiofffilho** [comment]
Thanks! It helps me. 

I was using a GearedValues in a ColumnSeries instead of GColumnSeries.
