### ISSUE TITLE
Geared Toolkit Crashes when updating data

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [beto-rodriguez/Live-Charts#734]
Instructions: replace text surrounded by '*' with your case, please delete this line.

#### How to reproduce?

*I'm adding additional values to the Value series using InsertRange.  On random occassions, the chart fails with a dialog box, 'Index was outside the bounds of the array'.  This works fine in the regular library, but the Geared library crashes (A LOT).  I'm sad that I upgraded*

*            <wpf:CartesianChart Grid.Row="1">
                <wpf:CartesianChart.Series>
                    <geared:GLineSeries Values="{Binding Financial}" x:Name="LineSeries"  PointGeometrySize="5" LineSmoothness="1" StrokeThickness="2" Stroke="Black" />
                    <geared:GOhlcSeries Values="{Binding Financial}" x:Name="OhlcSeries"/>
                    <geared:GScatterSeries Values="{Binding BreakoutHigh}" x:Name="BreakoutHigh" PointGeometry="{x:Static wpf:DefaultGeometries.Triangle}" Stroke="Green" StrokeThickness="2" />
                    <geared:GScatterSeries Values="{Binding BreakoutLow}" x:Name="BreakoutLow" PointGeometry="{x:Static wpf:DefaultGeometries.Cross}" Stroke="Purple" StrokeThickness="2"  /> 
                </wpf:CartesianChart.Series>
                <wpf:CartesianChart.AxisY>
                    <wpf:Axis Width="100" Title="Price" LabelFormatter="{Binding PriceFormatter}" Position="RightTop"></wpf:Axis>
                </wpf:CartesianChart.AxisY>
            </wpf:CartesianChart>
            <wpf:CartesianChart Grid.Row="2">
                <wpf:CartesianChart.Series>
                    <geared:GColumnSeries Values="{Binding Volume}" x:Name="VolumeSeries" />
                </wpf:CartesianChart.Series>
                <wpf:CartesianChart.AxisY>
                    <wpf:Axis Width="100" Title="Volume" LabelFormatter="{Binding VolumeFormatter}" Position="RightTop"></wpf:Axis>
                </wpf:CartesianChart.AxisY>
            </wpf:CartesianChart>*

#### Extra notes

*Dispatcher Unhandled Exception
System.IndexOutOfRangeException
Index was outside the bounds of the array.

   at LiveCharts.Geared.GearedValues`1.e.b()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LiveCharts.Geared.GearedValues`1.GetPoints(ISeriesView series)
   at LiveCharts.Geared.GearedValues`1.<>c.a(ISeriesView A_0)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LiveCharts.Geared.GearedValues`1.a(Chart A_0, Point A_1)
   at LiveCharts.Geared.GearedValues`1.a(Object A_0, MouseEventArgs A_1)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*Geared 5.4.1.0*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.6.1*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*10*</td>
</tr>
</table>

**Comment by ChrisLawford** [comment]
I have the same problem. Mine is just on the creation of the graph loading around 2000 points.
